spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/byamanda-db
    username: postgres
    # password: ${DB_PASSWORD}
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true